### ISSUE TITLE
Question on UIActivityIndicatorView compatibility

### ISSUE THREAD

**Issue by abadikaka** [AvdLee/SwiftUIKitView#1]
Hi, I have tried the library it is very perfectly if I am adding an UILabel or UIView. But now I am trying to add UIActivityIndicatorView, seems it doesn't work. Is this syntax below correct ?. I tried this but the view is not showing anything,  but once I try with UILabel or UIView, it works fine.

```
UIActivityIndicatorView(style: .large)
                .swiftUIView(layout: .fixed(size: CGSize(width: 100, height: 100)))
                .set(\.color, to: UIColor.blue)
                .set(\.isHidden, to: false)
                .fixedSize()
```                

second question, how did I trigger a function that preserved from one of the subclass of UIView ? Let say this activity indicator has an open function called as `startAnimating()`. however I can't using the declarative syntax in above code, is it expected to only set a value but can't call any derived method ?

Thank you before, @AvdLee

**Comment by AvdLee** [comment]
It might not be visible because it's not animating. It's likely better to wrap your activity indicator in a `UIViewRepresentable` and see if that works

**Comment by abadikaka** [comment]
Got it. I try with `UIViewRepresentable` and it is works.
I will closed this issues. Thank you @AvdLee
